In [906]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [907]:
df = pd.read_csv("Train_Data.csv")

In [908]:
df

pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0      y   83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      y  108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
2      E  169.65    0.0   5.6   73.5  14.5472  128.9295  13.6424  174.4680   
3      x  122.42   31.5   7.2   63.0  15.0152  119.8575  12.3344  186.8580   
4      E  125.43   94.5   7.2   42.0  14.4176  135.4290  14.5824  187.8135   
...   ..     ...    ...   ...    ...      ...       ...      ...       ...   
22579  E  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22580  x  156.74   63.0   5.6  105.0  13.6464  130.2000  12.4688  180.3690   
22581  w  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  y  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  E  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8       m9       m10      m11       m12      m13  \
0       8.9520  201.1905   9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385   8.4704  154.7805  13.3304  101.0205  12.5096   
2       8.9800  190.3125  11.3056  156.7650      NaN  122.5350  11.7136   
3      10.7208  193.8195  10.6096  175.7490      NaN  124.8030  13.8424   
4       9.3088  203.1540   9.8280  172.7040  14.4720  120.2145      NaN   
...        ...       ...      ...       ...      ...       ...      ...   
22579   8.6536  196.7490   9.2216  170.8770  17.3744  164.7240  12.5720   
22580  10.6984  212.6355   8.1152  167.8110  13.5656  129.5070  11.1344   
22581   9.6144  219.6810   9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610   7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970   9.0448  190.2495  16.4432  107.6355  12.7224   

            m14   ma  pred  
0      173.1240  m78     0  
1      131.4075  m78     0  
2      176.8200  m76     1  
3      168.2625  m55     0  
4      150.1185  m76     0  
...         ...  ...   ...  
22579  144.4065  m76     1  
22580       NaN  m55     1  
22581  153.5835  m78     0  
22582  158.0985  m78     0  
22583  169.7010  m76     0  

[22584 rows x 19 columns]

In [909]:
df['pc'].value_counts()

y    4915
E    4509
x    4414
z    4394
w    4352
Name: pc, dtype: int64

In [910]:
pc = np.array(df['pc'])

In [911]:
pc

array(['y', 'y', 'E', ..., 'w', 'y', 'E'], dtype=object)

In [912]:
for i in range(len(pc)):
  if(pc[i] == 'y'):
    pc[i] = 0
  if(pc[i] == 'E'):
    pc[i] = 1
  if(pc[i] == 'x'):
    pc[i] = 2
  if(pc[i] == 'z'):
    pc[i] = 3
  if(pc[i] == 'w'):
    pc[i] = 4

In [913]:
pc

array([0, 0, 1, ..., 4, 0, 1], dtype=object)

In [914]:
df.drop(['pc'],axis = 1,inplace = True)

In [915]:
df

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
2      169.65    0.0   5.6   73.5  14.5472  128.9295  13.6424  174.4680   
3      122.42   31.5   7.2   63.0  15.0152  119.8575  12.3344  186.8580   
4      125.43   94.5   7.2   42.0  14.4176  135.4290  14.5824  187.8135   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22580  156.74   63.0   5.6  105.0  13.6464  130.2000  12.4688  180.3690   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8       m9       m10      m11       m12      m13  \
0       8.9520  201.1905   9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385   8.4704  154.7805  13.3304  101.0205  12.5096   
2       8.9800  190.3125  11.3056  156.7650      NaN  122.5350  11.7136   
3      10.7208  193.8195  10.6096  175.7490      NaN  124.8030  13.8424   
4       9.3088  203.1540   9.8280  172.7040  14.4720  120.2145      NaN   
...        ...       ...      ...       ...      ...       ...      ...   
22579   8.6536  196.7490   9.2216  170.8770  17.3744  164.7240  12.5720   
22580  10.6984  212.6355   8.1152  167.8110  13.5656  129.5070  11.1344   
22581   9.6144  219.6810   9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610   7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970   9.0448  190.2495  16.4432  107.6355  12.7224   

            m14   ma  pred  
0      173.1240  m78     0  
1      131.4075  m78     0  
2      176.8200  m76     1  
3      168.2625  m55     0  
4      150.1185  m76     0  
...         ...  ...   ...  
22579  144.4065  m76     1  
22580       NaN  m55     1  
22581  153.5835  m78     0  
22582  158.0985  m78     0  
22583  169.7010  m76     0  

[22584 rows x 18 columns]

In [916]:
df['pc'] = pc

In [917]:
df

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
2      169.65    0.0   5.6   73.5  14.5472  128.9295  13.6424  174.4680   
3      122.42   31.5   7.2   63.0  15.0152  119.8575  12.3344  186.8580   
4      125.43   94.5   7.2   42.0  14.4176  135.4290  14.5824  187.8135   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22580  156.74   63.0   5.6  105.0  13.6464  130.2000  12.4688  180.3690   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8       m9       m10      m11       m12      m13  \
0       8.9520  201.1905   9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385   8.4704  154.7805  13.3304  101.0205  12.5096   
2       8.9800  190.3125  11.3056  156.7650      NaN  122.5350  11.7136   
3      10.7208  193.8195  10.6096  175.7490      NaN  124.8030  13.8424   
4       9.3088  203.1540   9.8280  172.7040  14.4720  120.2145      NaN   
...        ...       ...      ...       ...      ...       ...      ...   
22579   8.6536  196.7490   9.2216  170.8770  17.3744  164.7240  12.5720   
22580  10.6984  212.6355   8.1152  167.8110  13.5656  129.5070  11.1344   
22581   9.6144  219.6810   9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610   7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970   9.0448  190.2495  16.4432  107.6355  12.7224   

            m14   ma  pred pc  
0      173.1240  m78     0  0  
1      131.4075  m78     0  0  
2      176.8200  m76     1  1  
3      168.2625  m55     0  2  
4      150.1185  m76     0  1  
...         ...  ...   ... ..  
22579  144.4065  m76     1  1  
22580       NaN  m55     1  2  
22581  153.5835  m78     0  4  
22582  158.0985  m78     0  0  
22583  169.7010  m76     0  1  

[22584 rows x 19 columns]

In [918]:
df.dropna(inplace = True)

In [919]:
df

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
5      160.61   84.0  10.4   73.5  13.4656  121.3485  14.2832  188.7480   
7      136.55   73.5   9.6   94.5  14.1792  121.4430  13.8368  189.3465   
8      101.09   94.5   8.8  252.0  13.5632  109.3785  13.5984  185.8710   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22578  126.41   52.5   8.0   63.0  15.2552  133.0875  15.0120  191.3625   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8      m9       m10      m11       m12      m13  \
0       8.9520  201.1905  9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385  8.4704  154.7805  13.3304  101.0205  12.5096   
5      10.6888  195.7095  9.8808  167.1810  15.5344  103.9920  13.8584   
7       8.8304  211.2705  9.3368  165.4485  15.8424  124.3725  12.5552   
8       8.8368  188.7165  8.5168  163.4010  15.9320  113.0115  13.4072   
...        ...       ...     ...       ...      ...       ...      ...   
22578   9.8312  206.9340  9.4808  167.4960  14.1520   88.3575  12.1736   
22579   8.6536  196.7490  9.2216  170.8770  17.3744  164.7240  12.5720   
22581   9.6144  219.6810  9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610  7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970  9.0448  190.2495  16.4432  107.6355  12.7224   

            m14   ma  pred pc  
0      173.1240  m78     0  0  
1      131.4075  m78     0  0  
5      169.7850  m78     0  0  
7      158.0775  m75     0  3  
8      150.6120  m75     1  3  
...         ...  ...   ... ..  
22578  189.5670  m78     0  0  
22579  144.4065  m76     1  1  
22581  153.5835  m78     0  4  
22582  158.0985  m78     0  0  
22583  169.7010  m76     0  1  

[13298 rows x 19 columns]

In [920]:
df.dropna()

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
5      160.61   84.0  10.4   73.5  13.4656  121.3485  14.2832  188.7480   
7      136.55   73.5   9.6   94.5  14.1792  121.4430  13.8368  189.3465   
8      101.09   94.5   8.8  252.0  13.5632  109.3785  13.5984  185.8710   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22578  126.41   52.5   8.0   63.0  15.2552  133.0875  15.0120  191.3625   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8      m9       m10      m11       m12      m13  \
0       8.9520  201.1905  9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385  8.4704  154.7805  13.3304  101.0205  12.5096   
5      10.6888  195.7095  9.8808  167.1810  15.5344  103.9920  13.8584   
7       8.8304  211.2705  9.3368  165.4485  15.8424  124.3725  12.5552   
8       8.8368  188.7165  8.5168  163.4010  15.9320  113.0115  13.4072   
...        ...       ...     ...       ...      ...       ...      ...   
22578   9.8312  206.9340  9.4808  167.4960  14.1520   88.3575  12.1736   
22579   8.6536  196.7490  9.2216  170.8770  17.3744  164.7240  12.5720   
22581   9.6144  219.6810  9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610  7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970  9.0448  190.2495  16.4432  107.6355  12.7224   

            m14   ma  pred pc  
0      173.1240  m78     0  0  
1      131.4075  m78     0  0  
5      169.7850  m78     0  0  
7      158.0775  m75     0  3  
8      150.6120  m75     1  3  
...         ...  ...   ... ..  
22578  189.5670  m78     0  0  
22579  144.4065  m76     1  1  
22581  153.5835  m78     0  4  
22582  158.0985  m78     0  0  
22583  169.7010  m76     0  1  

[13298 rows x 19 columns]

In [921]:
ma = np.array(df['ma'])

In [922]:
ma_new = []
for i in range(len(ma)):
  ma_new.append(int(ma[i][1:]))

In [923]:
# ma_new

In [924]:
df.drop(['ma'],axis = 1,inplace = True)

In [925]:
df['ma'] = ma_new

In [926]:
df

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
5      160.61   84.0  10.4   73.5  13.4656  121.3485  14.2832  188.7480   
7      136.55   73.5   9.6   94.5  14.1792  121.4430  13.8368  189.3465   
8      101.09   94.5   8.8  252.0  13.5632  109.3785  13.5984  185.8710   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22578  126.41   52.5   8.0   63.0  15.2552  133.0875  15.0120  191.3625   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8      m9       m10      m11       m12      m13  \
0       8.9520  201.1905  9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385  8.4704  154.7805  13.3304  101.0205  12.5096   
5      10.6888  195.7095  9.8808  167.1810  15.5344  103.9920  13.8584   
7       8.8304  211.2705  9.3368  165.4485  15.8424  124.3725  12.5552   
8       8.8368  188.7165  8.5168  163.4010  15.9320  113.0115  13.4072   
...        ...       ...     ...       ...      ...       ...      ...   
22578   9.8312  206.9340  9.4808  167.4960  14.1520   88.3575  12.1736   
22579   8.6536  196.7490  9.2216  170.8770  17.3744  164.7240  12.5720   
22581   9.6144  219.6810  9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610  7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970  9.0448  190.2495  16.4432  107.6355  12.7224   

            m14  pred pc  ma  
0      173.1240     0  0  78  
1      131.4075     0  0  78  
5      169.7850     0  0  78  
7      158.0775     0  3  75  
8      150.6120     1  3  75  
...         ...   ... ..  ..  
22578  189.5670     0  0  78  
22579  144.4065     1  1  76  
22581  153.5835     0  4  78  
22582  158.0985     0  0  78  
22583  169.7010     0  1  76  

[13298 rows x 19 columns]

In [927]:
df.dropna(inplace = True)

In [928]:
df

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
5      160.61   84.0  10.4   73.5  13.4656  121.3485  14.2832  188.7480   
7      136.55   73.5   9.6   94.5  14.1792  121.4430  13.8368  189.3465   
8      101.09   94.5   8.8  252.0  13.5632  109.3785  13.5984  185.8710   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22578  126.41   52.5   8.0   63.0  15.2552  133.0875  15.0120  191.3625   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8      m9       m10      m11       m12      m13  \
0       8.9520  201.1905  9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385  8.4704  154.7805  13.3304  101.0205  12.5096   
5      10.6888  195.7095  9.8808  167.1810  15.5344  103.9920  13.8584   
7       8.8304  211.2705  9.3368  165.4485  15.8424  124.3725  12.5552   
8       8.8368  188.7165  8.5168  163.4010  15.9320  113.0115  13.4072   
...        ...       ...     ...       ...      ...       ...      ...   
22578   9.8312  206.9340  9.4808  167.4960  14.1520   88.3575  12.1736   
22579   8.6536  196.7490  9.2216  170.8770  17.3744  164.7240  12.5720   
22581   9.6144  219.6810  9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610  7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970  9.0448  190.2495  16.4432  107.6355  12.7224   

            m14  pred pc  ma  
0      173.1240     0  0  78  
1      131.4075     0  0  78  
5      169.7850     0  0  78  
7      158.0775     0  3  75  
8      150.6120     1  3  75  
...         ...   ... ..  ..  
22578  189.5670     0  0  78  
22579  144.4065     1  1  76  
22581  153.5835     0  4  78  
22582  158.0985     0  0  78  
22583  169.7010     0  1  76  

[13298 rows x 19 columns]

In [929]:
df.isnull().any()

ld      False
m0      False
m1      False
m2      False
m3      False
m4      False
m5      False
m6      False
m7      False
m8      False
m9      False
m10     False
m11     False
m12     False
m13     False
m14     False
pred    False
pc      False
ma      False
dtype: bool

In [930]:
y_train = df['pred']

In [931]:
df.drop(['pred'],axis = 1,inplace = True)

In [932]:
x = np.array(df)

In [933]:
x

array([[83.71, 63.0, 7.2, ..., 173.124, 0, 78],
       [108.94, 31.5, 12.8, ..., 131.4075, 0, 78],
       [160.61, 84.0, 10.4, ..., 169.785, 0, 78],
       ...,
       [115.63, 147.0, 4.8, ..., 153.5835, 4, 78],
       [216.26, 105.0, 4.8, ..., 158.0985, 0, 78],
       [120.65, 31.5, 6.4, ..., 169.701, 1, 76]], dtype=object)

In [934]:
len(y_train)

13298

In [935]:
a = []
for i in range(len(x)):
  a.append(list(x[i]))


In [936]:
for i in range(len(a)):
  a[i].append(1)

In [937]:
a = np.array(a)

In [938]:
a_new = []
for i in range(len(a)):
  a_new.append(a[i])
a_new

[array([ 83.71  ,  63.    ,   7.2   ,  52.5   ,  14.0232, 130.83  ,
         12.428 , 188.8425,   8.952 , 201.1905,   9.2896, 141.9075,
         16.0968, 150.339 ,  12.488 , 173.124 ,   0.    ,  78.    ,
          1.    ]),
 array([108.94  ,  31.5   ,  12.8   ,  84.    ,  13.284 , 128.835 ,
         13.5256, 183.099 ,   8.852 , 207.2385,   8.4704, 154.7805,
         13.3304, 101.0205,  12.5096, 131.4075,   0.    ,  78.    ,
          1.    ]),
 array([160.61  ,  84.    ,  10.4   ,  73.5   ,  13.4656, 121.3485,
         14.2832, 188.748 ,  10.6888, 195.7095,   9.8808, 167.181 ,
         15.5344, 103.992 ,  13.8584, 169.785 ,   0.    ,  78.    ,
          1.    ]),
 array([136.55  ,  73.5   ,   9.6   ,  94.5   ,  14.1792, 121.443 ,
         13.8368, 189.3465,   8.8304, 211.2705,   9.3368, 165.4485,
         15.8424, 124.3725,  12.5552, 158.0775,   3.    ,  75.    ,
          1.    ]),
 array([101.09  ,  94.5   ,   8.8   , 252.    ,  13.5632, 109.3785,
         13.5984, 185.871 ,   8.8368

In [939]:
a_transpose = np.transpose(a_new)

In [940]:
pseudo_a = np.dot((np.linalg.inv(np.dot(a_transpose, a_new))),np.transpose(a_new))

In [941]:
df.shape

(13298, 18)

In [942]:
x.shape

(13298, 18)

In [943]:
pseudo_a.shape

(19, 13298)

In [944]:
y_train = np.array(y_train)
y_train.shape

(13298,)

In [945]:
parameters = np.dot(pseudo_a ,y_train)

In [946]:
parameters.shape

(19,)

In [947]:
a_new[0].shape

(19,)

In [948]:
y_pred = []
for i in range(len(a)):
  y_pred.append(np.dot(np.transpose(parameters),a_new[i]))

In [949]:
threshold = np.median(y_pred)
threshold

0.2078168860426226

In [950]:
for i in range(len(y_pred)):
  if(y_pred[i] < threshold):
    y_pred[i] = 0
  else:
    y_pred[i] = 1

In [951]:
y_pred

[0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,


In [952]:
#Accuracy of the model
count = 0
for i in range(len(y_pred)):
  if(y_pred[i] == y_train[i]):
    count = count + 1

accuracy = (count/len(y_pred)) * 100
print(accuracy)

54.02316137765077


Testing data


In [953]:
data = pd.read_csv("Test_Data.csv")

In [954]:
data

index pc      ld     m0    m1     m2       m3        m4       m5  \
0         0  E  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552   
1         1  y   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688   
2         2  w  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544   
3         3  z  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080   
4         4  x  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936   
...     ... ..     ...    ...   ...    ...      ...       ...      ...   
3981   3981  z  109.45  126.0   4.0   94.5  14.6168  131.4495  13.1032   
3982   3982  w  188.31  136.5   1.6   21.0  12.9032  115.1535  14.3616   
3983   3983  E   80.99   31.5   4.8  115.5  15.0696  114.6810  14.0200   
3984   3984  w  120.64   42.0   0.8  126.0  13.8960  123.6585  13.5496   
3985   3985  w  115.73  199.5   4.0   10.5  14.2592  129.0555  13.8904   

            m6       m7        m8       m9       m10      m11       m12  \
0     168.5460   8.5896  187.6560   8.3472  178.5945  14.3192  138.0435   
1     190.6275  10.1712  202.5870   8.5416  166.9815  15.5944  142.5690   
2     168.3255  10.2504  214.2735  11.3392  155.1795  16.0256  132.1005   
3     196.6545  10.6304  213.4650   9.9224  191.1000  14.8256  128.0475   
4     168.3570   9.6184  191.2050   9.9400  185.0310  13.8664  124.7610   
...        ...      ...       ...      ...       ...      ...       ...   
3981  189.0840   8.3384  203.2275   9.6848       NaN  14.6384   97.2510   
3982  189.4830   7.6680  183.8865   9.8032  172.2945  16.1512  110.7330   
3983  186.0810   9.2080  193.6200   9.1600  170.1840      NaN  127.4700   
3984  187.8975   9.7944  189.0525   9.4752  173.0295  17.1728  113.0430   
3985  179.6865   8.8712  214.6410   8.8816  167.6535  15.4640  136.3635   

          m13       m14   ma  
0     12.7008  166.1100  m76  
1     11.6832  177.7230  m78  
2     13.0104  185.6085  m78  
3     12.1984  180.2745  m75  
4         NaN  157.6470  m55  
...       ...       ...  ...  
3981  12.3336  180.0435  m75  
3982  12.1680  204.5505  m78  
3983  13.5016       NaN  m76  
3984  13.1480  164.2410  m78  
3985  11.8728  178.5420  m78  

[3986 rows x 19 columns]

In [955]:
data.dropna(inplace = True)

In [956]:
data.isnull().any()

index    False
pc       False
ld       False
m0       False
m1       False
m2       False
m3       False
m4       False
m5       False
m6       False
m7       False
m8       False
m9       False
m10      False
m11      False
m12      False
m13      False
m14      False
ma       False
dtype: bool

In [957]:
data.drop(['index'],axis = 1,inplace = True)

In [958]:
data['pc'].value_counts()

x    522
y    502
E    465
w    421
z    409
Name: pc, dtype: int64

In [959]:
pc = np.array(data['pc'])
for i in range(len(pc)):
  if(pc[i] == 'y'):
    pc[i] = 0
  if(pc[i] == 'E'):
    pc[i] = 1
  if(pc[i] == 'x'):
    pc[i] = 2
  if(pc[i] == 'z'):
    pc[i] = 3
  if(pc[i] == 'w'):
    pc[i] = 4


In [960]:
pc

array([1, 0, 4, ..., 4, 4, 4], dtype=object)

In [961]:
data.drop(['pc'],axis = 1,inplace = True)

In [962]:
data['pc'] = pc

In [963]:
data

ld     m0    m1     m2       m3        m4       m5        m6  \
0     156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1      58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2     139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3     194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
5     135.43  105.0   6.4   10.5  15.7752  119.1855  13.4600  165.7740   
...      ...    ...   ...    ...      ...       ...      ...       ...   
3979  345.30  189.0   4.8   42.0  13.8976  110.5545  13.0384  181.9335   
3980   96.89  115.5   1.6   94.5  13.8528  113.4840  13.2184  177.2505   
3982  188.31  136.5   1.6   21.0  12.9032  115.1535  14.3616  189.4830   
3984  120.64   42.0   0.8  126.0  13.8960  123.6585  13.5496  187.8975   
3985  115.73  199.5   4.0   10.5  14.2592  129.0555  13.8904  179.6865   

           m7        m8       m9       m10      m11       m12      m13  \
0      8.5896  187.6560   8.3472  178.5945  14.3192  138.0435  12.7008   
1     10.1712  202.5870   8.5416  166.9815  15.5944  142.5690  11.6832   
2     10.2504  214.2735  11.3392  155.1795  16.0256  132.1005  13.0104   
3     10.6304  213.4650   9.9224  191.1000  14.8256  128.0475  12.1984   
5      9.6656  200.3190   9.3984  176.2740  15.8592  149.1840  13.6448   
...       ...       ...      ...       ...      ...       ...      ...   
3979   9.5344  190.2810   8.3128  163.9260  15.2344  108.3495  13.1488   
3980   8.8112  192.4545  10.5576  158.7915  16.7344  107.5620  12.4560   
3982   7.6680  183.8865   9.8032  172.2945  16.1512  110.7330  12.1680   
3984   9.7944  189.0525   9.4752  173.0295  17.1728  113.0430  13.1480   
3985   8.8712  214.6410   8.8816  167.6535  15.4640  136.3635  11.8728   

           m14   ma pc  
0     166.1100  m76  1  
1     177.7230  m78  0  
2     185.6085  m78  4  
3     180.2745  m75  3  
5     181.8075  m78  0  
...        ...  ... ..  
3979  169.3125  m78  0  
3980  200.2035  m78  4  
3982  204.5505  m78  4  
3984  164.2410  m78  4  
3985  178.5420  m78  4  

[2319 rows x 18 columns]

In [964]:
ma = np.array(data['ma'])

In [965]:
ma_new = []
for i in range(len(ma)):
  ma_new.append(int(ma[i][1:]))

In [966]:
# ma_new

In [967]:
data.drop(['ma'],axis = 1,inplace = True)

In [968]:
data['ma'] = ma_new

In [969]:
data

ld     m0    m1     m2       m3        m4       m5        m6  \
0     156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1      58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2     139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3     194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
5     135.43  105.0   6.4   10.5  15.7752  119.1855  13.4600  165.7740   
...      ...    ...   ...    ...      ...       ...      ...       ...   
3979  345.30  189.0   4.8   42.0  13.8976  110.5545  13.0384  181.9335   
3980   96.89  115.5   1.6   94.5  13.8528  113.4840  13.2184  177.2505   
3982  188.31  136.5   1.6   21.0  12.9032  115.1535  14.3616  189.4830   
3984  120.64   42.0   0.8  126.0  13.8960  123.6585  13.5496  187.8975   
3985  115.73  199.5   4.0   10.5  14.2592  129.0555  13.8904  179.6865   

           m7        m8       m9       m10      m11       m12      m13  \
0      8.5896  187.6560   8.3472  178.5945  14.3192  138.0435  12.7008   
1     10.1712  202.5870   8.5416  166.9815  15.5944  142.5690  11.6832   
2     10.2504  214.2735  11.3392  155.1795  16.0256  132.1005  13.0104   
3     10.6304  213.4650   9.9224  191.1000  14.8256  128.0475  12.1984   
5      9.6656  200.3190   9.3984  176.2740  15.8592  149.1840  13.6448   
...       ...       ...      ...       ...      ...       ...      ...   
3979   9.5344  190.2810   8.3128  163.9260  15.2344  108.3495  13.1488   
3980   8.8112  192.4545  10.5576  158.7915  16.7344  107.5620  12.4560   
3982   7.6680  183.8865   9.8032  172.2945  16.1512  110.7330  12.1680   
3984   9.7944  189.0525   9.4752  173.0295  17.1728  113.0430  13.1480   
3985   8.8712  214.6410   8.8816  167.6535  15.4640  136.3635  11.8728   

           m14 pc  ma  
0     166.1100  1  76  
1     177.7230  0  78  
2     185.6085  4  78  
3     180.2745  3  75  
5     181.8075  0  78  
...        ... ..  ..  
3979  169.3125  0  78  
3980  200.2035  4  78  
3982  204.5505  4  78  
3984  164.2410  4  78  
3985  178.5420  4  78  

[2319 rows x 18 columns]

In [970]:
x = np.array(data)

In [971]:
x

array([[156.46, 73.5, 8.8, ..., 166.11, 1, 76],
       [58.87, 84.0, 12.8, ..., 177.723, 0, 78],
       [139.68, 126.0, 3.2, ..., 185.6085, 4, 78],
       ...,
       [188.31, 136.5, 1.6, ..., 204.5505, 4, 78],
       [120.64, 42.0, 0.8, ..., 164.241, 4, 78],
       [115.73, 199.5, 4.0, ..., 178.542, 4, 78]], dtype=object)

In [972]:
x_test = []
for i in range(len(x)):
  x_test.append(list(x[i]))

In [973]:
for i in range(len(x_test)):
  x_test[i].append(1)

In [974]:
x_test = np.array(x_test)

In [975]:
x_test

array([[156.46,  73.5 ,   8.8 , ...,   1.  ,  76.  ,   1.  ],
       [ 58.87,  84.  ,  12.8 , ...,   0.  ,  78.  ,   1.  ],
       [139.68, 126.  ,   3.2 , ...,   4.  ,  78.  ,   1.  ],
       ...,
       [188.31, 136.5 ,   1.6 , ...,   4.  ,  78.  ,   1.  ],
       [120.64,  42.  ,   0.8 , ...,   4.  ,  78.  ,   1.  ],
       [115.73, 199.5 ,   4.  , ...,   4.  ,  78.  ,   1.  ]])

In [976]:
y_pred_test = []
for i in range(len(x_test)):
  y_pred_test.append(np.dot(np.transpose(parameters),x_test[i]))

In [977]:
y_pred_test

[0.23830292291271382,
 0.14188041851689626,
 0.2562010825047508,
 0.32091295893239,
 0.22031724420371257,
 0.16492850687046234,
 0.16965535084242156,
 0.16759324734485814,
 0.12371021194307785,
 0.13957107546866732,
 0.1753976999197413,
 0.2513977108533423,
 0.23938423801417885,
 0.2629386124455142,
 0.18346578962139537,
 0.31249128132253723,
 0.18674588809188764,
 0.34543868482387996,
 0.29905074290142764,
 0.1369291235774288,
 0.2520809505981335,
 0.21911431975917395,
 0.20150359627508407,
 0.24584898715225212,
 0.2276603775184085,
 0.23279231312630289,
 0.3046472200427368,
 0.15363779310811332,
 0.2679286077710188,
 0.31244167301384174,
 0.2645726449322423,
 0.1592174808837984,
 0.24531333195730565,
 0.16521079380928316,
 0.21901545166299252,
 0.20920908240278802,
 0.23493741805094814,
 0.16412482437183762,
 0.23891309846809994,
 0.21497072898861336,
 0.1735089285155218,
 0.274740205866975,
 0.27948709403196004,
 0.23734121009316622,
 0.22529416339933872,
 0.2887832218620823,
 0.224

In [978]:
threshold_test = np.median(y_pred_test)
for i in range(len(y_pred_test)):
  if(y_pred_test[i] < threshold_test):
    y_pred_test[i] = 0
  else:
    y_pred_test[i] = 1

In [979]:
y_pred_test

[1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
