In [189]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [190]:
df = pd.read_csv("Train_Data.csv")

In [191]:
df

pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0      y   83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      y  108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
2      E  169.65    0.0   5.6   73.5  14.5472  128.9295  13.6424  174.4680   
3      x  122.42   31.5   7.2   63.0  15.0152  119.8575  12.3344  186.8580   
4      E  125.43   94.5   7.2   42.0  14.4176  135.4290  14.5824  187.8135   
...   ..     ...    ...   ...    ...      ...       ...      ...       ...   
22579  E  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22580  x  156.74   63.0   5.6  105.0  13.6464  130.2000  12.4688  180.3690   
22581  w  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  y  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  E  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8       m9       m10      m11       m12      m13  \
0       8.9520  201.1905   9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385   8.4704  154.7805  13.3304  101.0205  12.5096   
2       8.9800  190.3125  11.3056  156.7650      NaN  122.5350  11.7136   
3      10.7208  193.8195  10.6096  175.7490      NaN  124.8030  13.8424   
4       9.3088  203.1540   9.8280  172.7040  14.4720  120.2145      NaN   
...        ...       ...      ...       ...      ...       ...      ...   
22579   8.6536  196.7490   9.2216  170.8770  17.3744  164.7240  12.5720   
22580  10.6984  212.6355   8.1152  167.8110  13.5656  129.5070  11.1344   
22581   9.6144  219.6810   9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610   7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970   9.0448  190.2495  16.4432  107.6355  12.7224   

            m14   ma  pred  
0      173.1240  m78     0  
1      131.4075  m78     0  
2      176.8200  m76     1  
3      168.2625  m55     0  
4      150.1185  m76     0  
...         ...  ...   ...  
22579  144.4065  m76     1  
22580       NaN  m55     1  
22581  153.5835  m78     0  
22582  158.0985  m78     0  
22583  169.7010  m76     0  

[22584 rows x 19 columns]

In [192]:
df.isnull().any()

pc      False
ld       True
m0      False
m1      False
m2      False
m3       True
m4       True
m5       True
m6       True
m7       True
m8       True
m9       True
m10      True
m11      True
m12      True
m13      True
m14      True
ma      False
pred    False
dtype: bool

In [193]:
mean_1d = df[df.columns[1]].mean()
df[df.columns[1]].fillna(value = mean_1d,inplace=True)

In [194]:
df.columns

Index(['pc', 'ld', 'm0', 'm1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9',
       'm10', 'm11', 'm12', 'm13', 'm14', 'ma', 'pred'],
      dtype='object')

In [195]:
mean_m3 = df['m3'].mean()
mean_m3

mean_m4 = df['m4'].mean()
mean_m5 = df['m5'].mean()
mean_m6 = df['m6'].mean()
mean_m7 = df['m7'].mean()
mean_m8 = df['m8'].mean()
mean_m9 = df['m9'].mean()
mean_m10 = df['m10'].mean()
mean_m11 = df['m11'].mean()
mean_m12 = df['m12'].mean()
mean_m13 = df['m13'].mean()
mean_m14 = df['m14'].mean()
df['m3'].fillna(value = mean_m3,inplace = True)
df['m4'].fillna(value = mean_m4,inplace = True)
df['m5'].fillna(value = mean_m5,inplace = True)
df['m6'].fillna(value = mean_m6,inplace = True)
df['m7'].fillna(value = mean_m7,inplace = True)
df['m8'].fillna(value = mean_m8,inplace = True)
df['m9'].fillna(value = mean_m9,inplace = True)
df['m10'].fillna(value = mean_m10,inplace = True)
df['m11'].fillna(value = mean_m11,inplace = True)
df['m12'].fillna(value = mean_m12,inplace = True)
df['m13'].fillna(value = mean_m13,inplace = True)
df['m14'].fillna(value = mean_m14,inplace = True)

In [196]:
df['pc'].value_counts()

y    4915
E    4509
x    4414
z    4394
w    4352
Name: pc, dtype: int64

In [197]:
pc = np.array(df['pc'])

In [198]:
pc

array(['y', 'y', 'E', ..., 'w', 'y', 'E'], dtype=object)

In [199]:
for i in range(len(pc)):
  if(pc[i] == 'y'):
    pc[i] = 0
  if(pc[i] == 'E'):
    pc[i] = 1
  if(pc[i] == 'x'):
    pc[i] = 2
  if(pc[i] == 'z'):
    pc[i] = 3
  if(pc[i] == 'w'):
    pc[i] = 4

In [200]:
pc

array([0, 0, 1, ..., 4, 0, 1], dtype=object)

In [201]:
df.drop(['pc'],axis = 1,inplace = True)

In [202]:
df

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
2      169.65    0.0   5.6   73.5  14.5472  128.9295  13.6424  174.4680   
3      122.42   31.5   7.2   63.0  15.0152  119.8575  12.3344  186.8580   
4      125.43   94.5   7.2   42.0  14.4176  135.4290  14.5824  187.8135   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22580  156.74   63.0   5.6  105.0  13.6464  130.2000  12.4688  180.3690   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8       m9       m10        m11       m12        m13  \
0       8.9520  201.1905   9.2896  141.9075  16.096800  150.3390  12.488000   
1       8.8520  207.2385   8.4704  154.7805  13.330400  101.0205  12.509600   
2       8.9800  190.3125  11.3056  156.7650  15.334764  122.5350  11.713600   
3      10.7208  193.8195  10.6096  175.7490  15.334764  124.8030  13.842400   
4       9.3088  203.1540   9.8280  172.7040  14.472000  120.2145  12.521853   
...        ...       ...      ...       ...        ...       ...        ...   
22579   8.6536  196.7490   9.2216  170.8770  17.374400  164.7240  12.572000   
22580  10.6984  212.6355   8.1152  167.8110  13.565600  129.5070  11.134400   
22581   9.6144  219.6810   9.3120  156.7440  15.971200  109.3680  12.848000   
22582   9.0160  200.3610   7.4760  174.7830  16.788800  135.1770  12.733600   
22583  10.0600  192.2970   9.0448  190.2495  16.443200  107.6355  12.722400   

              m14   ma  pred  
0      173.124000  m78     0  
1      131.407500  m78     0  
2      176.820000  m76     1  
3      168.262500  m55     0  
4      150.118500  m76     0  
...           ...  ...   ...  
22579  144.406500  m76     1  
22580  168.530817  m55     1  
22581  153.583500  m78     0  
22582  158.098500  m78     0  
22583  169.701000  m76     0  

[22584 rows x 18 columns]

In [203]:
df['pc'] = pc

In [204]:
df

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
2      169.65    0.0   5.6   73.5  14.5472  128.9295  13.6424  174.4680   
3      122.42   31.5   7.2   63.0  15.0152  119.8575  12.3344  186.8580   
4      125.43   94.5   7.2   42.0  14.4176  135.4290  14.5824  187.8135   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22580  156.74   63.0   5.6  105.0  13.6464  130.2000  12.4688  180.3690   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8       m9       m10        m11       m12        m13  \
0       8.9520  201.1905   9.2896  141.9075  16.096800  150.3390  12.488000   
1       8.8520  207.2385   8.4704  154.7805  13.330400  101.0205  12.509600   
2       8.9800  190.3125  11.3056  156.7650  15.334764  122.5350  11.713600   
3      10.7208  193.8195  10.6096  175.7490  15.334764  124.8030  13.842400   
4       9.3088  203.1540   9.8280  172.7040  14.472000  120.2145  12.521853   
...        ...       ...      ...       ...        ...       ...        ...   
22579   8.6536  196.7490   9.2216  170.8770  17.374400  164.7240  12.572000   
22580  10.6984  212.6355   8.1152  167.8110  13.565600  129.5070  11.134400   
22581   9.6144  219.6810   9.3120  156.7440  15.971200  109.3680  12.848000   
22582   9.0160  200.3610   7.4760  174.7830  16.788800  135.1770  12.733600   
22583  10.0600  192.2970   9.0448  190.2495  16.443200  107.6355  12.722400   

              m14   ma  pred pc  
0      173.124000  m78     0  0  
1      131.407500  m78     0  0  
2      176.820000  m76     1  1  
3      168.262500  m55     0  2  
4      150.118500  m76     0  1  
...           ...  ...   ... ..  
22579  144.406500  m76     1  1  
22580  168.530817  m55     1  2  
22581  153.583500  m78     0  4  
22582  158.098500  m78     0  0  
22583  169.701000  m76     0  1  

[22584 rows x 19 columns]

In [205]:
ma = np.array(df['ma'])

In [206]:
ma_new = []
for i in range(len(ma)):
  ma_new.append(int(ma[i][1:]))

In [207]:
# ma_new

In [208]:
df.drop(['ma'],axis = 1,inplace = True)

In [209]:
df['ma'] = ma_new

In [210]:
df

ld     m0    m1     m2       m3        m4       m5        m6  \
0       83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
2      169.65    0.0   5.6   73.5  14.5472  128.9295  13.6424  174.4680   
3      122.42   31.5   7.2   63.0  15.0152  119.8575  12.3344  186.8580   
4      125.43   94.5   7.2   42.0  14.4176  135.4290  14.5824  187.8135   
...       ...    ...   ...    ...      ...       ...      ...       ...   
22579  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22580  156.74   63.0   5.6  105.0  13.6464  130.2000  12.4688  180.3690   
22581  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8       m9       m10        m11       m12        m13  \
0       8.9520  201.1905   9.2896  141.9075  16.096800  150.3390  12.488000   
1       8.8520  207.2385   8.4704  154.7805  13.330400  101.0205  12.509600   
2       8.9800  190.3125  11.3056  156.7650  15.334764  122.5350  11.713600   
3      10.7208  193.8195  10.6096  175.7490  15.334764  124.8030  13.842400   
4       9.3088  203.1540   9.8280  172.7040  14.472000  120.2145  12.521853   
...        ...       ...      ...       ...        ...       ...        ...   
22579   8.6536  196.7490   9.2216  170.8770  17.374400  164.7240  12.572000   
22580  10.6984  212.6355   8.1152  167.8110  13.565600  129.5070  11.134400   
22581   9.6144  219.6810   9.3120  156.7440  15.971200  109.3680  12.848000   
22582   9.0160  200.3610   7.4760  174.7830  16.788800  135.1770  12.733600   
22583  10.0600  192.2970   9.0448  190.2495  16.443200  107.6355  12.722400   

              m14  pred pc  ma  
0      173.124000     0  0  78  
1      131.407500     0  0  78  
2      176.820000     1  1  76  
3      168.262500     0  2  55  
4      150.118500     0  1  76  
...           ...   ... ..  ..  
22579  144.406500     1  1  76  
22580  168.530817     1  2  55  
22581  153.583500     0  4  78  
22582  158.098500     0  0  78  
22583  169.701000     0  1  76  

[22584 rows x 19 columns]

In [211]:
y_train = df['pred']

In [212]:
df.drop(['pred'],axis = 1,inplace = True)

In [213]:
x = np.array(df)

In [214]:
x

array([[83.71, 63.0, 7.2, ..., 173.124, 0, 78],
       [108.94, 31.5, 12.8, ..., 131.4075, 0, 78],
       [169.65, 0.0, 5.6, ..., 176.82, 1, 76],
       ...,
       [115.63, 147.0, 4.8, ..., 153.5835, 4, 78],
       [216.26, 105.0, 4.8, ..., 158.0985, 0, 78],
       [120.65, 31.5, 6.4, ..., 169.701, 1, 76]], dtype=object)

In [215]:
len(y_train)

22584

In [216]:
a = []
for i in range(len(x)):
  a.append(list(x[i]))


In [217]:
for i in range(len(a)):
  a[i].append(1)

In [218]:
a = np.array(a)

In [219]:
a_new = []
for i in range(len(a)):
  a_new.append(a[i])
a_new

[array([ 83.71  ,  63.    ,   7.2   ,  52.5   ,  14.0232, 130.83  ,
         12.428 , 188.8425,   8.952 , 201.1905,   9.2896, 141.9075,
         16.0968, 150.339 ,  12.488 , 173.124 ,   0.    ,  78.    ,
          1.    ]),
 array([108.94  ,  31.5   ,  12.8   ,  84.    ,  13.284 , 128.835 ,
         13.5256, 183.099 ,   8.852 , 207.2385,   8.4704, 154.7805,
         13.3304, 101.0205,  12.5096, 131.4075,   0.    ,  78.    ,
          1.    ]),
 array([169.65      ,   0.        ,   5.6       ,  73.5       ,
         14.5472    , 128.9295    ,  13.6424    , 174.468     ,
          8.98      , 190.3125    ,  11.3056    , 156.765     ,
         15.33476421, 122.535     ,  11.7136    , 176.82      ,
          1.        ,  76.        ,   1.        ]),
 array([122.42      ,  31.5       ,   7.2       ,  63.        ,
         15.0152    , 119.8575    ,  12.3344    , 186.858     ,
         10.7208    , 193.8195    ,  10.6096    , 175.749     ,
         15.33476421, 124.803     ,  13.8424    , 16

In [220]:
a_transpose = np.transpose(a_new)

In [221]:
pseudo_a = np.dot((np.linalg.inv(np.dot(a_transpose, a_new))),np.transpose(a_new))

In [222]:
df.shape

(22584, 18)

In [223]:
x.shape

(22584, 18)

In [224]:
pseudo_a.shape

(19, 22584)

In [225]:
y_train = np.array(y_train)
y_train.shape

(22584,)

In [226]:
parameters = np.dot(pseudo_a ,y_train)

In [227]:
parameters.shape

(19,)

In [228]:
a_new[0].shape

(19,)

In [229]:
y_pred = []
for i in range(len(a)):
  y_pred.append(np.dot(np.transpose(parameters),a_new[i]))

In [230]:
threshold = np.median(y_pred)
threshold

0.20887967905101396

In [231]:
for i in range(len(y_pred)):
  if(y_pred[i] < threshold):
    y_pred[i] = 0
  else:
    y_pred[i] = 1

In [232]:
y_pred

[0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,


In [233]:
#Accuracy of the model
count = 0
for i in range(len(y_pred)):
  if(y_pred[i] == y_train[i]):
    count = count + 1

print(count)
print(len(y_pred))
accuracy = (count/len(y_pred)) * 100
print(accuracy)

12301
22584
54.46776478923131


Testing data


In [234]:
data = pd.read_csv("Test_Data.csv")

In [235]:
data

index pc      ld     m0    m1     m2       m3        m4       m5  \
0         0  E  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552   
1         1  y   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688   
2         2  w  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544   
3         3  z  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080   
4         4  x  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936   
...     ... ..     ...    ...   ...    ...      ...       ...      ...   
3981   3981  z  109.45  126.0   4.0   94.5  14.6168  131.4495  13.1032   
3982   3982  w  188.31  136.5   1.6   21.0  12.9032  115.1535  14.3616   
3983   3983  E   80.99   31.5   4.8  115.5  15.0696  114.6810  14.0200   
3984   3984  w  120.64   42.0   0.8  126.0  13.8960  123.6585  13.5496   
3985   3985  w  115.73  199.5   4.0   10.5  14.2592  129.0555  13.8904   

            m6       m7        m8       m9       m10      m11       m12  \
0     168.5460   8.5896  187.6560   8.3472  178.5945  14.3192  138.0435   
1     190.6275  10.1712  202.5870   8.5416  166.9815  15.5944  142.5690   
2     168.3255  10.2504  214.2735  11.3392  155.1795  16.0256  132.1005   
3     196.6545  10.6304  213.4650   9.9224  191.1000  14.8256  128.0475   
4     168.3570   9.6184  191.2050   9.9400  185.0310  13.8664  124.7610   
...        ...      ...       ...      ...       ...      ...       ...   
3981  189.0840   8.3384  203.2275   9.6848       NaN  14.6384   97.2510   
3982  189.4830   7.6680  183.8865   9.8032  172.2945  16.1512  110.7330   
3983  186.0810   9.2080  193.6200   9.1600  170.1840      NaN  127.4700   
3984  187.8975   9.7944  189.0525   9.4752  173.0295  17.1728  113.0430   
3985  179.6865   8.8712  214.6410   8.8816  167.6535  15.4640  136.3635   

          m13       m14   ma  
0     12.7008  166.1100  m76  
1     11.6832  177.7230  m78  
2     13.0104  185.6085  m78  
3     12.1984  180.2745  m75  
4         NaN  157.6470  m55  
...       ...       ...  ...  
3981  12.3336  180.0435  m75  
3982  12.1680  204.5505  m78  
3983  13.5016       NaN  m76  
3984  13.1480  164.2410  m78  
3985  11.8728  178.5420  m78  

[3986 rows x 19 columns]

In [236]:
data.isnull().any()

index    False
pc       False
ld        True
m0       False
m1       False
m2       False
m3        True
m4        True
m5        True
m6        True
m7        True
m8        True
m9        True
m10       True
m11       True
m12       True
m13       True
m14       True
ma       False
dtype: bool

In [237]:
mean_m3 = data['m3'].mean()
mean_m4 = data['m4'].mean()
mean_m5 = data['m5'].mean()
mean_m6 = data['m6'].mean()
mean_m7 = data['m7'].mean()
mean_m8 = data['m8'].mean()
mean_m9 = data['m9'].mean()
mean_m10 = data['m10'].mean()
mean_m11 = data['m11'].mean()
mean_m12 = data['m12'].mean()
mean_m13 = data['m13'].mean()
mean_m14 = data['m14'].mean()
mean_1d = data[data.columns[2]].mean()
data['m3'].fillna(value = mean_m3,inplace = True)
data['m4'].fillna(value = mean_m4,inplace = True)
data['m5'].fillna(value = mean_m5,inplace = True)
data['m6'].fillna(value = mean_m6,inplace = True)
data['m7'].fillna(value = mean_m7,inplace = True)
data['m8'].fillna(value = mean_m8,inplace = True)
data['m9'].fillna(value = mean_m9,inplace = True)
data['m10'].fillna(value = mean_m10,inplace = True)
data['m11'].fillna(value = mean_m11,inplace = True)
data['m12'].fillna(value = mean_m12,inplace = True)
data['m13'].fillna(value = mean_m13,inplace = True)
data['m14'].fillna(value = mean_m14,inplace = True)
data[data.columns[2]].fillna(value = mean_1d,inplace = True)

In [238]:
data.drop(['index'],axis = 1,inplace = True)

In [239]:
data['pc'].value_counts()

y    850
x    836
E    834
w    748
z    718
Name: pc, dtype: int64

In [240]:
pc = np.array(data['pc'])
for i in range(len(pc)):
  if(pc[i] == 'y'):
    pc[i] = 0
  if(pc[i] == 'E'):
    pc[i] = 1
  if(pc[i] == 'x'):
    pc[i] = 2
  if(pc[i] == 'z'):
    pc[i] = 3
  if(pc[i] == 'w'):
    pc[i] = 4


In [241]:
pc

array([1, 0, 4, ..., 1, 4, 4], dtype=object)

In [242]:
data.drop(['pc'],axis = 1,inplace = True)

In [243]:
data['pc'] = pc

In [244]:
data

ld     m0    m1     m2       m3        m4       m5        m6  \
0     156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1      58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2     139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3     194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
4     173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   
...      ...    ...   ...    ...      ...       ...      ...       ...   
3981  109.45  126.0   4.0   94.5  14.6168  131.4495  13.1032  189.0840   
3982  188.31  136.5   1.6   21.0  12.9032  115.1535  14.3616  189.4830   
3983   80.99   31.5   4.8  115.5  15.0696  114.6810  14.0200  186.0810   
3984  120.64   42.0   0.8  126.0  13.8960  123.6585  13.5496  187.8975   
3985  115.73  199.5   4.0   10.5  14.2592  129.0555  13.8904  179.6865   

           m7        m8       m9         m10       m11       m12        m13  \
0      8.5896  187.6560   8.3472  178.594500  14.31920  138.0435  12.700800   
1     10.1712  202.5870   8.5416  166.981500  15.59440  142.5690  11.683200   
2     10.2504  214.2735  11.3392  155.179500  16.02560  132.1005  13.010400   
3     10.6304  213.4650   9.9224  191.100000  14.82560  128.0475  12.198400   
4      9.6184  191.2050   9.9400  185.031000  13.86640  124.7610  12.524991   
...       ...       ...      ...         ...       ...       ...        ...   
3981   8.3384  203.2275   9.6848  169.215523  14.63840   97.2510  12.333600   
3982   7.6680  183.8865   9.8032  172.294500  16.15120  110.7330  12.168000   
3983   9.2080  193.6200   9.1600  170.184000  15.35423  127.4700  13.501600   
3984   9.7944  189.0525   9.4752  173.029500  17.17280  113.0430  13.148000   
3985   8.8712  214.6410   8.8816  167.653500  15.46400  136.3635  11.872800   

             m14   ma pc  
0     166.110000  m76  1  
1     177.723000  m78  0  
2     185.608500  m78  4  
3     180.274500  m75  3  
4     157.647000  m55  2  
...          ...  ... ..  
3981  180.043500  m75  3  
3982  204.550500  m78  4  
3983  168.382988  m76  1  
3984  164.241000  m78  4  
3985  178.542000  m78  4  

[3986 rows x 18 columns]

In [245]:
ma = np.array(data['ma'])

In [246]:
ma_new = []
for i in range(len(ma)):
  ma_new.append(int(ma[i][1:]))

In [247]:
# ma_new

In [248]:
data.drop(['ma'],axis = 1,inplace = True)

In [249]:
data['ma'] = ma_new

In [250]:
data

ld     m0    m1     m2       m3        m4       m5        m6  \
0     156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1      58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2     139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3     194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
4     173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   
...      ...    ...   ...    ...      ...       ...      ...       ...   
3981  109.45  126.0   4.0   94.5  14.6168  131.4495  13.1032  189.0840   
3982  188.31  136.5   1.6   21.0  12.9032  115.1535  14.3616  189.4830   
3983   80.99   31.5   4.8  115.5  15.0696  114.6810  14.0200  186.0810   
3984  120.64   42.0   0.8  126.0  13.8960  123.6585  13.5496  187.8975   
3985  115.73  199.5   4.0   10.5  14.2592  129.0555  13.8904  179.6865   

           m7        m8       m9         m10       m11       m12        m13  \
0      8.5896  187.6560   8.3472  178.594500  14.31920  138.0435  12.700800   
1     10.1712  202.5870   8.5416  166.981500  15.59440  142.5690  11.683200   
2     10.2504  214.2735  11.3392  155.179500  16.02560  132.1005  13.010400   
3     10.6304  213.4650   9.9224  191.100000  14.82560  128.0475  12.198400   
4      9.6184  191.2050   9.9400  185.031000  13.86640  124.7610  12.524991   
...       ...       ...      ...         ...       ...       ...        ...   
3981   8.3384  203.2275   9.6848  169.215523  14.63840   97.2510  12.333600   
3982   7.6680  183.8865   9.8032  172.294500  16.15120  110.7330  12.168000   
3983   9.2080  193.6200   9.1600  170.184000  15.35423  127.4700  13.501600   
3984   9.7944  189.0525   9.4752  173.029500  17.17280  113.0430  13.148000   
3985   8.8712  214.6410   8.8816  167.653500  15.46400  136.3635  11.872800   

             m14 pc  ma  
0     166.110000  1  76  
1     177.723000  0  78  
2     185.608500  4  78  
3     180.274500  3  75  
4     157.647000  2  55  
...          ... ..  ..  
3981  180.043500  3  75  
3982  204.550500  4  78  
3983  168.382988  1  76  
3984  164.241000  4  78  
3985  178.542000  4  78  

[3986 rows x 18 columns]

In [251]:
x = np.array(data)

In [252]:
x

array([[156.46, 73.5, 8.8, ..., 166.11, 1, 76],
       [58.87, 84.0, 12.8, ..., 177.723, 0, 78],
       [139.68, 126.0, 3.2, ..., 185.6085, 4, 78],
       ...,
       [80.99, 31.5, 4.8, ..., 168.38298757092676, 1, 76],
       [120.64, 42.0, 0.8, ..., 164.241, 4, 78],
       [115.73, 199.5, 4.0, ..., 178.542, 4, 78]], dtype=object)

In [253]:
x_test = []
for i in range(len(x)):
  x_test.append(list(x[i]))

In [254]:
for i in range(len(x_test)):
  x_test[i].append(1)

In [255]:
x_test = np.array(x_test)

In [256]:
x_test

array([[156.46,  73.5 ,   8.8 , ...,   1.  ,  76.  ,   1.  ],
       [ 58.87,  84.  ,  12.8 , ...,   0.  ,  78.  ,   1.  ],
       [139.68, 126.  ,   3.2 , ...,   4.  ,  78.  ,   1.  ],
       ...,
       [ 80.99,  31.5 ,   4.8 , ...,   1.  ,  76.  ,   1.  ],
       [120.64,  42.  ,   0.8 , ...,   4.  ,  78.  ,   1.  ],
       [115.73, 199.5 ,   4.  , ...,   4.  ,  78.  ,   1.  ]])

In [257]:
y_pred_test = []
for i in range(len(x_test)):
  y_pred_test.append(np.dot(np.transpose(parameters),x_test[i]))

In [258]:
y_pred_test

[0.24882913709839122,
 0.12802783618066033,
 0.265802377504822,
 0.3406925170812793,
 0.2750471927109635,
 0.2121080851719031,
 0.2784382289368618,
 0.16680560391706406,
 0.18430327626101767,
 0.1613417195438433,
 0.11147109734503341,
 0.15255279932855553,
 0.1699984039089792,
 0.25190891614727967,
 0.1903960626308458,
 0.29988533871550577,
 0.23803092262315556,
 0.29452103992303197,
 0.18498318775552608,
 0.18751873432230953,
 0.3102103973430221,
 0.21068315574023438,
 0.33649370625100333,
 0.2364774619378111,
 0.21469727669295863,
 0.3531978229614207,
 0.2898387979725802,
 0.13565410435353437,
 0.3256097794476231,
 0.2639507426384811,
 0.21695515436778262,
 0.190767000998546,
 0.21998818654080193,
 0.17711254666341553,
 0.23521431160055056,
 0.2248283158449818,
 0.2367691975257467,
 0.1984483194805267,
 0.16697532001437204,
 0.2566994711852753,
 0.1528319009826195,
 0.1963349434132357,
 0.16303205360640977,
 0.35539225489383236,
 0.3086278938752544,
 0.15384556704606028,
 0.266498396

In [259]:
threshold_test = np.median(y_pred_test)
for i in range(len(y_pred_test)):
  if(y_pred_test[i] < threshold_test):
    y_pred_test[i] = 0
  else:
    y_pred_test[i] = 1

In [260]:
y_pred_test

[1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
